### ISSUE TITLE
Deploy PDS API v0 (alpha) on pds-gamma test server

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#13]

**Comment by tloubrieu-jpl** [comment]
The software is deployed and accessible https://pds-gamma.jpl.nasa.gov/api/swagger-ui.html

A request for security scan has been made through Thompson, Aaron C (US 173B-Affiliate) <aaron.c.thompson@jpl.nasa.gov> so that it is open.

Apparently the server did not start up automatically at some point although Rojeh set up start/stop for this service. @tloubrieu-jpl  checks with him what happened.

**Comment by tloubrieu-jpl** [comment]
delayed:1 because security scan is not done yet so to open to public

**Comment by tloubrieu-jpl** [comment]
Email sent to Aaron and Rojeh for updates regarding the security scan. Service is not public yet.

**Comment by tloubrieu-jpl** [comment]
Service is now open on https://pds-gamma.jpl.nasa.gov/api/swagger-ui.html
