### ISSUE TITLE
Improve linkages from Registry App Docs to API Docs

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#158]
- [x] overall improvements to documentation from registry to API for new users
- [ ] update client docs with links to jupyter notebooks for examples
- [x] update client docs with improved title casing
- [x] stopgap improvement https://github.com/NASA-PDS/pds-registry-app/issues/158

**Comment by tloubrieu-jpl** [comment]
For "overall improvements to documentation from registry to API for new users" see note on https://nasa-pds.github.io/registry/

I am not linking the jupyter notebook yet because we don't have an API server yet which contains the data the notebooks have been developed for. A new ticket is created for that https://github.com/NASA-PDS/pds-api/issues/178
