### ISSUE TITLE
version number invalid according to PEP validation in CI

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#164]
## 🐛 Describe the bug

See https://github.com/NASA-PDS/pds-api/runs/5325706010?check_suite_focus=true#step:5:342

**Comment by tloubrieu-jpl** [comment]
This issue has been solved as well as others so that the CICD works on this repository and enables to publish the documentation whenever a stable release is tagged.

Main commit is https://github.com/NASA-PDS/pds-api/commit/957d1420d3a71065dad9cf1acc2c885945481ac4

See successful github action  https://github.com/NASA-PDS/pds-api/actions/runs/1918253014
