### ISSUE TITLE
As a developer, I never want the label blob to be returned

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-api#80]
## Motivation
...so that I simplify the amount of metadata/data returned by the API + the API should handle translating this via content negotiation and some other response, not through the returned metadata.

## Acceptance Criteria
**Given** a deployed API with label blobs ingested
**When I perform** a query for a data product
**Then I expect** to return the associated metadata product, but NOT the blob

**Comment by al-niessner** [comment]
@jordanpadams @tloubrieu-jpl 

- Do you mean this label: ops:Label_File_Info/ops:blob
- Do you mean this label: *blob*

As a design idea, you can put the blobs themselves storage (s3 or some filesystem area) with the filename md5sum_sha2sum to make them all unique. The blob metadata in the database would then be the filename which is small and remove the need for the extra filtering. It would also speed up database performance too. Downside is blobs are separated from the database requiring two areas to be backed up.

**Comment by tloubrieu-jpl** [comment]
Hi @al-niessner , @jordanpadams , I was thinking I will work on this one. @al-niessner  you can do it but this ticket is blocked by https://github.com/nasa-pds/registry-api-service/issues/27 and https://github.com/NASA-PDS/pds-api/issues/66 on which I am working now.

The reason is that the xml format currently requires the blob to be in the returned elasticsearch object. I will work on the xml encoding so that it is not required anymore.


The

**Comment by jordanpadams** [comment]
copy that @tloubrieu-jpl . didn't realize these were so tightly coupled. 

@al-niessner we can get started on this one instead: nasa-pds/registry-api-service#13
